package view;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.io.IOException;
import java.net.URL;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;
import javax.swing.Painter;
import javax.swing.UIDefaults;

import model.LivroUsuario;

/**
 *
 * @author gabriel
 */
public class LivroEmprestadoView extends javax.swing.JPanel {

    private Image background;

    /**
     * Creates new form LivroView
     * 
     * @param titulo
     * @param autor
     * @param dataEmprestimo
     * @param dataPrazo
     * @param status
     */
    public LivroEmprestadoView(LivroUsuario livroUsuario) {
        initComponents();
        loadBackground();
        loadImage(livroUsuario.getLivro().getPathImagem());
        overrideLookAndFeel();
        txtTitulo.setText(livroUsuario.getLivro().getTitulo());
        txtAutor.setText(livroUsuario.getLivro().getAutor());
        txtDiaEmprestimo.setText(livroUsuario.getDataEmprestimo());
        txtPrazoVencimento.setText(livroUsuario.getPrazo());
        txtStatus.setText(livroUsuario.isExpirado()? "Expirado" : "Em dia");
    }

    private void overrideLookAndFeel(){
        UIDefaults overrides = new UIDefaults();
        overrides.put("TextArea[Disabled].backgroundPainter", new Painter<JTextArea>() {

            @Override
            public void paint(Graphics2D g, JTextArea field, int width, int height) {
                g.setColor(new Color(67, 35, 17, 230));
                g.fill(new Rectangle(
                        0, 
                        0, 
                        width ,  // Tirar tudo pra ficar sem borda
                        height));
            }
        });
        txtTitulo.putClientProperty("Nimbus.Overrides", overrides);
        txtAutor.putClientProperty("Nimbus.Overrides", overrides);
        txtDiaEmprestimo.putClientProperty("Nimbus.Overrides", overrides);
        txtPrazoVencimento.putClientProperty("Nimbus.Overrides", overrides);
        txtStatus.putClientProperty("Nimbus.Overrides", overrides);
    }

    private void loadBackground(){
        try {
            this.background = ImageIO.read(new URL(getClass().getResource("/images/livroBackground4.png"), "livroBackground4.png"));
        } catch (IOException e) {
            System.err.println("ERRO: " + e.getMessage());
        }
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (background!= null) {
            // Redimensiona a imagem para cobrir toda a área do painel
            Image scaledImg = background.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_DEFAULT);
            g.drawImage(scaledImg, 0, 0, this);
        }
    }

    private void loadImage(String path){

        int width = 300;
        int height = 400;

        try {
            // Carrega e redimensiona a imagem do livro
            ImageIcon imageIconLivro = new ImageIcon(getClass().getResource(path));
            if (imageIconLivro!= null) {
                Image imageLivro = imageIconLivro.getImage();
                Image scaledImageLivro = imageLivro.getScaledInstance(width, height, Image.SCALE_SMOOTH);
                ImageIcon scaledIconLivro = new ImageIcon(scaledImageLivro);
                lblImage.setIcon(scaledIconLivro);
            }
        } catch (Exception e) {
            System.err.println("Erro na obtencao da imagem: " + e.getMessage());
            lblImage.setText("                                    Image not found");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageBackground = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTitulo = new javax.swing.JTextArea();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPrazoVencimento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPrazoVencimento = new javax.swing.JTextArea();
        lblStatus = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtStatus = new javax.swing.JTextArea();
        lblDiaEmprestimo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDiaEmprestimo = new javax.swing.JTextArea();
        lblAutor = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAutor = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(67, 35, 17));
        setPreferredSize(new java.awt.Dimension(800, 450));

        imageBackground.setBackground(new java.awt.Color(204, 141, 72));
        imageBackground.setPreferredSize(new java.awt.Dimension(300, 420));

        javax.swing.GroupLayout imageBackgroundLayout = new javax.swing.GroupLayout(imageBackground);
        imageBackground.setLayout(imageBackgroundLayout);
        imageBackgroundLayout.setHorizontalGroup(
            imageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        imageBackgroundLayout.setVerticalGroup(
            imageBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        txtTitulo.setEditable(false);
        txtTitulo.setColumns(20);
        txtTitulo.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        txtTitulo.setLineWrap(true);
        txtTitulo.setRows(1);
        txtTitulo.setWrapStyleWord(true);
        txtTitulo.setDisabledTextColor(new java.awt.Color(220, 220, 220));
        txtTitulo.setEnabled(false);
        jScrollPane1.setViewportView(txtTitulo);

        lblTitulo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 204, 204));
        lblTitulo.setText("Título:");

        lblPrazoVencimento.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblPrazoVencimento.setForeground(new java.awt.Color(204, 204, 204));
        lblPrazoVencimento.setText("Prazo de vencimento:");

        txtPrazoVencimento.setEditable(false);
        txtPrazoVencimento.setColumns(20);
        txtPrazoVencimento.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        txtPrazoVencimento.setLineWrap(true);
        txtPrazoVencimento.setRows(1);
        txtPrazoVencimento.setWrapStyleWord(true);
        txtPrazoVencimento.setDisabledTextColor(new java.awt.Color(220, 220, 220));
        txtPrazoVencimento.setEnabled(false);
        jScrollPane2.setViewportView(txtPrazoVencimento);

        lblStatus.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(204, 204, 204));
        lblStatus.setText("Status:");

        txtStatus.setEditable(false);
        txtStatus.setColumns(20);
        txtStatus.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        txtStatus.setLineWrap(true);
        txtStatus.setRows(1);
        txtStatus.setWrapStyleWord(true);
        txtStatus.setDisabledTextColor(new java.awt.Color(220, 220, 220));
        txtStatus.setEnabled(false);
        jScrollPane3.setViewportView(txtStatus);

        lblDiaEmprestimo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblDiaEmprestimo.setForeground(new java.awt.Color(204, 204, 204));
        lblDiaEmprestimo.setText("Dia do empréstimo:");

        txtDiaEmprestimo.setEditable(false);
        txtDiaEmprestimo.setColumns(20);
        txtDiaEmprestimo.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        txtDiaEmprestimo.setLineWrap(true);
        txtDiaEmprestimo.setRows(1);
        txtDiaEmprestimo.setWrapStyleWord(true);
        txtDiaEmprestimo.setDisabledTextColor(new java.awt.Color(220, 220, 220));
        txtDiaEmprestimo.setEnabled(false);
        jScrollPane5.setViewportView(txtDiaEmprestimo);

        lblAutor.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblAutor.setForeground(new java.awt.Color(204, 204, 204));
        lblAutor.setText("Autor:");

        txtAutor.setEditable(false);
        txtAutor.setColumns(20);
        txtAutor.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        txtAutor.setLineWrap(true);
        txtAutor.setRows(1);
        txtAutor.setWrapStyleWord(true);
        txtAutor.setDisabledTextColor(new java.awt.Color(220, 220, 220));
        txtAutor.setEnabled(false);
        jScrollPane6.setViewportView(txtAutor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitulo)
                                    .addComponent(lblPrazoVencimento)
                                    .addComponent(lblStatus)
                                    .addComponent(lblDiaEmprestimo)
                                    .addComponent(lblAutor))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane2))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDiaEmprestimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrazoVencimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imageBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel imageBackground;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblDiaEmprestimo;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPrazoVencimento;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtAutor;
    private javax.swing.JTextArea txtDiaEmprestimo;
    private javax.swing.JTextArea txtPrazoVencimento;
    private javax.swing.JTextArea txtStatus;
    private javax.swing.JTextArea txtTitulo;
    // End of variables declaration//GEN-END:variables
}
