/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicTabbedPaneUI;

import controller.UsuarioDAO;
import images.ImagePanel;
import model.Usuario;

/**
 *
 * @author gabriel
 */
public class MainFrame extends javax.swing.JFrame {

    protected static Usuario usuarioLogado;

    /**
     * Creates new form UsuarioView
     */
    public MainFrame() {
        //this.setContentPane(new ImagePanel());
        initComponents();
        configureLoginPaneWithBackground();
        configureTabbedPaneUI();
        loadIcons();
        setLocationRelativeTo(null);
        setResizable(false); 
        setTitle("BIBLIOTECA");
    }

    private void configureLoginPaneWithBackground() {
        // Crie um objeto ImagePanel
        ImagePanel background = new ImagePanel();
        
        // Torna o painel de login transparente
        paneLogin.setOpaque(false);
        //paneLogin.getComponent(0).setOpaque(false); // Repita isso para todos os componentes filhos
        // Defina o layout do painel de login para BorderLayout
        paneLogin.setLayout(new BorderLayout());
        
        // Adicione o painel de login ao painel de imagem
        background.add(paneLogin, BorderLayout.CENTER);
        
        // Substitua o painel de login original pelo painel de imagem
        tbPane.remove(paneLogin);
        tbPane.insertTab("Login", null, background, null, 0);
        tbPane.setSelectedIndex(0);
    }

    private void configureTabbedPaneUI() {
        tbPane.setUI(new BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tab_placement, int run_count, int max_tab_height) {
                return -1;
            }
        });
        tbPane.setEnabledAt(0, true);
        tbPane.setEnabledAt(1, false);
        tbPane.setEnabledAt(2, false);
    }

    private void loadIcons() {

        int homeIconWidth = 40;
        int homeIconHeight = 40;
    
        try {
            // Carrega e redimensiona a imagem para iconSair
            ImageIcon imageIconSair = new ImageIcon(getClass().getResource("/images/logout.png"));
            if (imageIconSair!= null) {
                Image imageSair = imageIconSair.getImage();
                Image scaledImageSair = imageSair.getScaledInstance(homeIconWidth, homeIconHeight, Image.SCALE_SMOOTH);
                ImageIcon scaledIconSair = new ImageIcon(scaledImageSair);
                iconSair.setIcon(scaledIconSair);
            }
        } catch (Exception e) {
            System.err.println("Imagem 'logout.png' nao existe, usando fallback textual!");
            iconSair.setText("Sair");
        }

        try {
            // Carrega e redimensiona a imagem para iconConfig
            ImageIcon imageIconConfig = new ImageIcon(getClass().getResource("/images/setting.png")); 
            if (imageIconConfig!= null) {
                Image imageConfig = imageIconConfig.getImage();
                Image scaledImageConfig = imageConfig.getScaledInstance(homeIconWidth, homeIconHeight, Image.SCALE_SMOOTH);
                ImageIcon scaledIconConfig = new ImageIcon(scaledImageConfig);
                iconConfig.setIcon(scaledIconConfig);
            }
        } catch (Exception e) {
            System.err.println("Imagem 'setting.png' nao existe, usando fallback textual!");
            iconConfig.setText("Conf");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbPane = new javax.swing.JTabbedPane();
        paneLogin = new javax.swing.JPanel();
        lblLogin_paneLogin = new javax.swing.JLabel();
        lblNome_paneLogin = new javax.swing.JLabel();
        txtNome_paneLogin = new javax.swing.JTextField();
        lblSenha_paneLogin = new javax.swing.JLabel();
        btnEntrar_paneLogin = new javax.swing.JButton();
        lblNoConta_paneLogin = new javax.swing.JLabel();
        lblCadastre_paneLogin = new javax.swing.JLabel();
        txtSenha_paneLogin = new javax.swing.JPasswordField();
        paneCadastro = new javax.swing.JPanel();
        lblCadastro_paneCadastro = new javax.swing.JLabel();
        lblNome_paneCadastro = new javax.swing.JLabel();
        txtNome_paneCadastro = new javax.swing.JTextField();
        lblEmail_paneCadastro = new javax.swing.JLabel();
        txtEmail_paneCadastro = new javax.swing.JTextField();
        lblSenha_paneCadastro = new javax.swing.JLabel();
        txtSenha_paneCadastro = new javax.swing.JPasswordField();
        lblConfirmarSenha_paneCadastro = new javax.swing.JLabel();
        txtConfirmarSenha_paneCadastro = new javax.swing.JPasswordField();
        btnCadastrar_paneCadastro = new javax.swing.JButton();
        lblRetornarLogin_paneCadastro = new javax.swing.JLabel();
        paneHome = new javax.swing.JPanel();
        lblMenu_paneMenu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblBusca_paneMenu = new javax.swing.JLabel();
        btnBuscar_paneMenu = new javax.swing.JButton();
        lblOperacoes_paneMenu = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnEmprestimo_paneMenu = new javax.swing.JButton();
        btnDevolucao_paneMenu = new javax.swing.JButton();
        btnRenovar_paneMenu = new javax.swing.JButton();
        btnLivrosEscolhidos_paneMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoBusca_paneMenu = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricaoOp_paneMenu = new javax.swing.JTextArea();
        iconSair = new javax.swing.JLabel();
        iconConfig = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 550));

        paneLogin.setPreferredSize(new java.awt.Dimension(700, 550));

        lblLogin_paneLogin.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblLogin_paneLogin.setText("LOGIN");

        lblNome_paneLogin.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblNome_paneLogin.setText("Nome ou Email");

        txtNome_paneLogin.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtNome_paneLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNome_paneLoginFocusGained(evt);
            }
        });

        lblSenha_paneLogin.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblSenha_paneLogin.setText("Senha");

        btnEntrar_paneLogin.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnEntrar_paneLogin.setText("Entrar");
        btnEntrar_paneLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar_paneLoginActionPerformed(evt);
            }
        });

        lblNoConta_paneLogin.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblNoConta_paneLogin.setText("Não possui conta?");

        lblCadastre_paneLogin.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblCadastre_paneLogin.setForeground(new java.awt.Color(0, 0, 255));
        lblCadastre_paneLogin.setText("Cadastre-se");
        lblCadastre_paneLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCadastre_paneLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastre_paneLoginMouseClicked(evt);
            }
        });

        txtSenha_paneLogin.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtSenha_paneLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenha_paneLoginFocusGained(evt);
            }
        });

        javax.swing.GroupLayout paneLoginLayout = new javax.swing.GroupLayout(paneLogin);
        paneLogin.setLayout(paneLoginLayout);
        paneLoginLayout.setHorizontalGroup(
            paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLoginLayout.createSequentialGroup()
                .addGap(0, 171, Short.MAX_VALUE)
                .addGroup(paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNome_paneLogin)
                    .addComponent(txtNome_paneLogin)
                    .addComponent(lblSenha_paneLogin)
                    .addComponent(txtSenha_paneLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(169, 169, 169))
            .addGroup(paneLoginLayout.createSequentialGroup()
                .addGroup(paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneLoginLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(lblLogin_paneLogin))
                    .addGroup(paneLoginLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(lblNoConta_paneLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCadastre_paneLogin))
                    .addGroup(paneLoginLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(btnEntrar_paneLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneLoginLayout.setVerticalGroup(
            paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin_paneLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(lblNome_paneLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome_paneLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSenha_paneLogin)
                .addGap(18, 18, 18)
                .addComponent(txtSenha_paneLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnEntrar_paneLogin)
                .addGap(57, 57, 57)
                .addGroup(paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoConta_paneLogin)
                    .addComponent(lblCadastre_paneLogin))
                .addGap(18, 18, 18))
        );

        tbPane.addTab("Login", paneLogin);

        lblCadastro_paneCadastro.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblCadastro_paneCadastro.setText("CADASTRO");

        lblNome_paneCadastro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblNome_paneCadastro.setText("Nome");

        txtNome_paneCadastro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        lblEmail_paneCadastro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblEmail_paneCadastro.setText("Email");

        txtEmail_paneCadastro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        lblSenha_paneCadastro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblSenha_paneCadastro.setText("Senha");

        txtSenha_paneCadastro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        lblConfirmarSenha_paneCadastro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblConfirmarSenha_paneCadastro.setText("Confirmar senha");

        txtConfirmarSenha_paneCadastro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        btnCadastrar_paneCadastro.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnCadastrar_paneCadastro.setText("Cadastrar");
        btnCadastrar_paneCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar_paneCadastroActionPerformed(evt);
            }
        });

        lblRetornarLogin_paneCadastro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblRetornarLogin_paneCadastro.setForeground(new java.awt.Color(0, 51, 255));
        lblRetornarLogin_paneCadastro.setText("Retornar ao Login");
        lblRetornarLogin_paneCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRetornarLogin_paneCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRetornarLogin_paneCadastroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneCadastroLayout = new javax.swing.GroupLayout(paneCadastro);
        paneCadastro.setLayout(paneCadastroLayout);
        paneCadastroLayout.setHorizontalGroup(
            paneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastroLayout.createSequentialGroup()
                .addGroup(paneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCadastroLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(lblCadastro_paneCadastro))
                    .addGroup(paneCadastroLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(paneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblConfirmarSenha_paneCadastro)
                            .addComponent(lblSenha_paneCadastro)
                            .addComponent(lblEmail_paneCadastro)
                            .addComponent(txtEmail_paneCadastro)
                            .addComponent(lblNome_paneCadastro)
                            .addComponent(txtNome_paneCadastro)
                            .addComponent(txtSenha_paneCadastro)
                            .addComponent(txtConfirmarSenha_paneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneCadastroLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(paneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRetornarLogin_paneCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadastrar_paneCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        paneCadastroLayout.setVerticalGroup(
            paneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastro_paneCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome_paneCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome_paneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEmail_paneCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail_paneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSenha_paneCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSenha_paneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblConfirmarSenha_paneCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtConfirmarSenha_paneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar_paneCadastro)
                .addGap(18, 18, 18)
                .addComponent(lblRetornarLogin_paneCadastro)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tbPane.addTab("Cadastro", paneCadastro);

        lblMenu_paneMenu.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblMenu_paneMenu.setText("MENU DE OPÇÕES");

        jSeparator1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N

        lblBusca_paneMenu.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblBusca_paneMenu.setForeground(new java.awt.Color(153, 153, 153));
        lblBusca_paneMenu.setText("Busca");

        btnBuscar_paneMenu.setFont(new java.awt.Font("sansserif", 0, 22)); // NOI18N
        btnBuscar_paneMenu.setText("Buscar Livros Disponíveis");
        btnBuscar_paneMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscar_paneMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscar_paneMenuMouseExited(evt);
            }
        });
        btnBuscar_paneMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar_paneMenuActionPerformed(evt);
            }
        });

        lblOperacoes_paneMenu.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblOperacoes_paneMenu.setForeground(new java.awt.Color(153, 153, 153));
        lblOperacoes_paneMenu.setText("Operações");

        jSeparator2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N

        btnEmprestimo_paneMenu.setFont(new java.awt.Font("sansserif", 0, 22)); // NOI18N
        btnEmprestimo_paneMenu.setText("Empréstimo de Livros ");
        btnEmprestimo_paneMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmprestimo_paneMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmprestimo_paneMenuMouseExited(evt);
            }
        });
        btnEmprestimo_paneMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimo_paneMenuActionPerformed(evt);
            }
        });

        btnDevolucao_paneMenu.setFont(new java.awt.Font("sansserif", 0, 22)); // NOI18N
        btnDevolucao_paneMenu.setText("Devolução de Livros");
        btnDevolucao_paneMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDevolucao_paneMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDevolucao_paneMenuMouseExited(evt);
            }
        });
        btnDevolucao_paneMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucao_paneMenuActionPerformed(evt);
            }
        });

        btnRenovar_paneMenu.setFont(new java.awt.Font("sansserif", 0, 22)); // NOI18N
        btnRenovar_paneMenu.setText("Renovar ");
        btnRenovar_paneMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRenovar_paneMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRenovar_paneMenuMouseExited(evt);
            }
        });
        btnRenovar_paneMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenovar_paneMenuActionPerformed(evt);
            }
        });

        btnLivrosEscolhidos_paneMenu.setFont(new java.awt.Font("sansserif", 0, 22)); // NOI18N
        btnLivrosEscolhidos_paneMenu.setText("Ver Livros Emprestados");
        btnLivrosEscolhidos_paneMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLivrosEscolhidos_paneMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLivrosEscolhidos_paneMenuMouseExited(evt);
            }
        });
        btnLivrosEscolhidos_paneMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivrosEscolhidos_paneMenuActionPerformed(evt);
            }
        });

        txtDescricaoBusca_paneMenu.setEditable(false);
        txtDescricaoBusca_paneMenu.setColumns(1);
        txtDescricaoBusca_paneMenu.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtDescricaoBusca_paneMenu.setLineWrap(true);
        txtDescricaoBusca_paneMenu.setRows(2);
        txtDescricaoBusca_paneMenu.setWrapStyleWord(true);
        txtDescricaoBusca_paneMenu.setEnabled(false);
        jScrollPane1.setViewportView(txtDescricaoBusca_paneMenu);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtDescricaoOp_paneMenu.setEditable(false);
        txtDescricaoOp_paneMenu.setColumns(1);
        txtDescricaoOp_paneMenu.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtDescricaoOp_paneMenu.setLineWrap(true);
        txtDescricaoOp_paneMenu.setRows(5);
        txtDescricaoOp_paneMenu.setWrapStyleWord(true);
        txtDescricaoOp_paneMenu.setEnabled(false);
        jScrollPane2.setViewportView(txtDescricaoOp_paneMenu);

        iconSair.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        iconSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconSairMouseClicked(evt);
            }
        });

        iconConfig.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        iconConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout paneHomeLayout = new javax.swing.GroupLayout(paneHome);
        paneHome.setLayout(paneHomeLayout);
        paneHomeLayout.setHorizontalGroup(
            paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHomeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneHomeLayout.createSequentialGroup()
                        .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEmprestimo_paneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(btnDevolucao_paneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRenovar_paneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHomeLayout.createSequentialGroup()
                            .addComponent(lblOperacoes_paneMenu)
                            .addGap(18, 18, 18)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(paneHomeLayout.createSequentialGroup()
                                .addComponent(iconSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(lblMenu_paneMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iconConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneHomeLayout.createSequentialGroup()
                                .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnLivrosEscolhidos_paneMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscar_paneMenu, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneHomeLayout.createSequentialGroup()
                                .addComponent(lblBusca_paneMenu)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        paneHomeLayout.setVerticalGroup(
            paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMenu_paneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconConfig, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBusca_paneMenu)
                    .addGroup(paneHomeLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneHomeLayout.createSequentialGroup()
                        .addComponent(btnBuscar_paneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLivrosEscolhidos_paneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOperacoes_paneMenu)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneHomeLayout.createSequentialGroup()
                        .addComponent(btnEmprestimo_paneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDevolucao_paneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRenovar_paneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tbPane.addTab("Home", paneHome);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbPane, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * MÉTODOS DE EVENTOS
     * 
     **/
    /*CADASTRO*************************************************************************/
    private void btnCadastrar_paneCadastroActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        
        if(txtSenha_paneCadastro.getText().equals(txtConfirmarSenha_paneCadastro.getText())){

            Usuario u = new Usuario(txtNome_paneCadastro.getText(), txtEmail_paneCadastro.getText(), new String(txtSenha_paneCadastro.getPassword()));
            UsuarioDAO dao = new UsuarioDAO();
    
            if (dao.inserirNovoUsuario(u) != -1) {
                JOptionPane.showMessageDialog(null, "Cadastro realizado");
                txtNome_paneCadastro.setText("");
                txtEmail_paneCadastro.setText("");
                txtSenha_paneCadastro.setText("");
                txtConfirmarSenha_paneCadastro.setText("");
                tbPane.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar");
            }
        } else {
            lblConfirmarSenha_paneCadastro.setForeground(Color.RED);
            txtConfirmarSenha_paneCadastro.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Senhas não correspondem");
        }

    }

    private void lblRetornarLogin_paneCadastroMouseClicked(java.awt.event.MouseEvent evt) {   
        txtNome_paneCadastro.setText("");
        txtEmail_paneCadastro.setText("");
        txtSenha_paneCadastro.setText("");
        txtConfirmarSenha_paneCadastro.setText("");                                                        
        tbPane.setSelectedIndex(0);
        tbPane.setEnabledAt(0, true);
        tbPane.setEnabledAt(1, false);
        tbPane.setEnabledAt(2, false);
    }

    /*FIM-CADASTRO*************************************************************************/

    /*LOGIN*************************************************************************/
    private void btnEntrar_paneLoginActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        
        String nomeEmail = txtNome_paneLogin.getText();
        String senha = new String(txtSenha_paneLogin.getPassword());
        UsuarioDAO dao = new UsuarioDAO();

        if(!senha.isEmpty() && !nomeEmail.isEmpty()){
            usuarioLogado = dao.acessarUsuario(nomeEmail, senha);
            System.out.println(usuarioLogado);
            if (usuarioLogado == null){
                txtNome_paneLogin.setForeground(Color.RED);
                txtSenha_paneLogin.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Usuário ou Senha inválidos");
            } else {
                txtNome_paneLogin.setText("");
                txtSenha_paneLogin.setText("");
                tbPane.setSelectedIndex(2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para entrar!");
        }
    }

    private void lblCadastre_paneLoginMouseClicked(java.awt.event.MouseEvent evt) {                                                   
        tbPane.setSelectedIndex(1);
        tbPane.setEnabledAt(0, false);
        tbPane.setEnabledAt(1, true);
        tbPane.setEnabledAt(2, false);
    }

    private void txtNome_paneLoginFocusGained(java.awt.event.FocusEvent evt) {                                              
        txtNome_paneLogin.setForeground(Color.BLACK);
    }

    private void txtSenha_paneLoginFocusGained(java.awt.event.FocusEvent evt) {                                               

        txtSenha_paneLogin.setForeground(Color.BLACK);
    }

    /*FIM-LOGIN*************************************************************************/

    /*HOME*************************************************************************/
    private void btnBuscar_paneMenuActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }

    private void btnEmprestimo_paneMenuActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }

    private void btnDevolucao_paneMenuActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }

    private void btnRenovar_paneMenuActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }

    private void btnLivrosEscolhidos_paneMenuActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
    }

    private void btnBuscar_paneMenuMouseEntered(java.awt.event.MouseEvent evt) {                                                
        txtDescricaoBusca_paneMenu.setText("Veja todos os livros disponíveis no acervo!");
    }

    private void btnBuscar_paneMenuMouseExited(java.awt.event.MouseEvent evt) {
        txtDescricaoBusca_paneMenu.setText("");
    }

    private void btnLivrosEscolhidos_paneMenuMouseEntered(java.awt.event.MouseEvent evt) {
        txtDescricaoBusca_paneMenu.setText("Veja os livros em sua posse e o prazo de devulução!");
    }

    private void btnLivrosEscolhidos_paneMenuMouseExited(java.awt.event.MouseEvent evt) {
        txtDescricaoBusca_paneMenu.setText("");
    }

    private void btnEmprestimo_paneMenuMouseEntered(java.awt.event.MouseEvent evt) {
        txtDescricaoOp_paneMenu.setText("Clique para realizar o empréstimo de algum livro de seu interesse!");
    }

    private void btnEmprestimo_paneMenuMouseExited(java.awt.event.MouseEvent evt) {
        txtDescricaoOp_paneMenu.setText("");
    }

    private void btnDevolucao_paneMenuMouseEntered(java.awt.event.MouseEvent evt) {
        txtDescricaoOp_paneMenu.setText("Clique para realizar a devolução de um livro em sua posse!");
    }

    private void btnDevolucao_paneMenuMouseExited(java.awt.event.MouseEvent evt) {
        txtDescricaoOp_paneMenu.setText("");
    }

    private void btnRenovar_paneMenuMouseEntered(java.awt.event.MouseEvent evt) {
        txtDescricaoOp_paneMenu.setText("Renove aqui o empréstimo do livro!");
    }

    private void btnRenovar_paneMenuMouseExited(java.awt.event.MouseEvent evt) {
        txtDescricaoOp_paneMenu.setText("");
    }      
    
    private void iconSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconSairMouseClicked
        int resposta = JOptionPane.showConfirmDialog(
             null,
             "Você precisará fazer o login novamente ao sair",
             "Deseja realmente sair?",
             JOptionPane.YES_NO_OPTION
             );

        if(resposta == JOptionPane.YES_OPTION){
            tbPane.setSelectedIndex(0);
            tbPane.setEnabledAt(0, true);
            tbPane.setEnabledAt(1, false);
            tbPane.setEnabledAt(2, false);
            usuarioLogado = null;
        }

    }//GEN-LAST:event_iconSairMouseClicked

    

    /**             
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame frame = new MainFrame();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar_paneMenu;
    private javax.swing.JButton btnCadastrar_paneCadastro;
    private javax.swing.JButton btnDevolucao_paneMenu;
    private javax.swing.JButton btnEmprestimo_paneMenu;
    private javax.swing.JButton btnEntrar_paneLogin;
    private javax.swing.JButton btnLivrosEscolhidos_paneMenu;
    private javax.swing.JButton btnRenovar_paneMenu;
    private javax.swing.JLabel iconConfig;
    private javax.swing.JLabel iconSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBusca_paneMenu;
    private javax.swing.JLabel lblCadastre_paneLogin;
    private javax.swing.JLabel lblCadastro_paneCadastro;
    private javax.swing.JLabel lblConfirmarSenha_paneCadastro;
    private javax.swing.JLabel lblEmail_paneCadastro;
    private javax.swing.JLabel lblLogin_paneLogin;
    private javax.swing.JLabel lblMenu_paneMenu;
    private javax.swing.JLabel lblNoConta_paneLogin;
    private javax.swing.JLabel lblNome_paneCadastro;
    private javax.swing.JLabel lblNome_paneLogin;
    private javax.swing.JLabel lblOperacoes_paneMenu;
    private javax.swing.JLabel lblRetornarLogin_paneCadastro;
    private javax.swing.JLabel lblSenha_paneCadastro;
    private javax.swing.JLabel lblSenha_paneLogin;
    private javax.swing.JPanel paneCadastro;
    private javax.swing.JPanel paneHome;
    private javax.swing.JPanel paneLogin;
    private javax.swing.JTabbedPane tbPane;
    private javax.swing.JPasswordField txtConfirmarSenha_paneCadastro;
    private javax.swing.JTextArea txtDescricaoBusca_paneMenu;
    private javax.swing.JTextArea txtDescricaoOp_paneMenu;
    private javax.swing.JTextField txtEmail_paneCadastro;
    private javax.swing.JTextField txtNome_paneCadastro;
    private javax.swing.JTextField txtNome_paneLogin;
    private javax.swing.JPasswordField txtSenha_paneCadastro;
    private javax.swing.JPasswordField txtSenha_paneLogin;
    // End of variables declaration//GEN-END:variables
}
